language: node_js
node_js:
  - node
  - iojs
  - 0.1
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - "0.10"
  - 0.11
  - 0.12
  - 5
  - 6
  - 7
  - stable
  - unstable
  - lts/*
  - lts/argon
  - lts/boron
script:
  - bash info.sh
